version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile  
    image: gerador-resumo-api:dev
    env_file:
      - .env
    ports:
      - "${HOST_PORT:-8080}:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    working_dir: /app
    restart: unless-stopped
